services:
  mongo:
    image: mongo:8
    container_name: eventos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always
  
  # api:
  #    container_name: eventos-api
  #    build: .
  #    ports:
  #      - "${API_PORT}:${API_PORT}"
  #    env_file:
  #      - ./.env
  #    depends_on:
  #      - mongo
    
volumes:
  mongo-data:
