# docker-compose.dev.yml

services:
  # Serviço da API em modo desenvolvimento
  api:
    container_name: eventos-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - TERM=xterm
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon --legacy-watch server.js
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: eventos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

volumes:
  mongo-data-dev:
