# docker-compose.dev.yml

services:
  # Serviço da API em modo desenvolvimento
  api:
    container_name: eventos-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - TERM=xterm
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon --legacy-watch server.js
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: eventos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

  mailsender:
    container_name: mailsender-service
    build:
      context: ./mailsender
      dockerfile: Dockerfile
    env_file:
      - ./mailsender/.env
    ports:
      - "5013:5013"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5013/"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mongo-data-dev: