version: "3.8"
services:
  mail_api_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail_api_service
    restart: always
    volumes:
      - ./:/usr/src/app # monta o seu projeto inteiro

    # Usa a mesma porta definida no .env (3010 → 3010)
    ports:
      - "${PORT}:${PORT}"

    # Passa TODAS as variáveis do .env para dentro do contêiner
    env_file:
      - .env

    # Health-check simples
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/"]
      interval: 30s
      timeout: 5s
      retries: 3
